### ISSUE TITLE
frontend npm upstream dependency conflict installing npm packages

### ISSUE THREAD

**Issue by emito-k** [COS301-SE-2023/xPOSE#137]
So everytime we install new packages in the frontend, npm ERR messages appear especially with animation libraries and such

**Comment by emito-k** [comment]
Hopefully running the command ```npm install --legacy-peer-deps``` should resolve the problem

https://stackoverflow.com/questions/64936044/fix-the-upstream-dependency-conflict-installing-npm-packages

**Comment by sovaria10** [comment]
It works.
