### ISSUE TITLE
Usermanagement-ervice sql connection in API being refused

### ISSUE THREAD

**Issue by Ibango7** [COS301-SE-2023/xPOSE#17]
When a user signs up the UID should be stored in the sql table.

Querying the sql table to insert uid in the createUser API function is being refused
but if I test it outside of the createUser function on its own file it works.
Please note that the sql query functionality is being imported and used int the createUpser API function.

**Comment by emito-k** [comment]
One possible solution is to edit the package.json inside the user management service, removing the type attribute. That way you can just stick with using only require, and exporting using `module.exports` for your code

**Comment by Ibango7** [comment]
Thanks for the feedback but that aspect has been solved. It is no longer an issue. I can connect to sql alright but the moment I import the connection file to the  create user it becomes an issue feedback " sql connection forbidden."
If I do query inside of the connection file it works fine but the moment Import the file to where I need to use it, the connection is forbidden.

**Comment by Ibango7** [comment]
Fixed
