### ISSUE TITLE
Side bar and  menu at footer conflict

### ISSUE THREAD

**Issue by Ibango7** [COS301-SE-2023/xPOSE#173]
I noticed that after I have pulled code, that the menu at the footer had been removed, 
I attempted to put it back and realized that there is a conflict with the side bar I presume this is the reason why it has been removed in the first place??

So to not spend much  time, I have put the menu at the footer as it was previously without including the dedicated component<app-footer> until it is solved.
Please note I have not pushed such changes

**Comment by emito-k** [comment]
Solved
