### ISSUE TITLE
Set up Discord

### ISSUE THREAD

**Issue by emmanuella08** [COS301-SE-2023/xPOSE#4]
Create a Discord server and invite the client to join for easier communication and updates. Channels for:
- [x] Frontend
- [x] Backend
- [x] Cloud
- [x] Firebase
- [x] AI
- [x] Admin
- [x] Add client

**Comment by emmanuella08** [comment]
Add frontend channel, documentation, meetings, dev-ops, data engineering channels

**Comment by emmanuella08** [comment]
meetings agenda under administration not channel

**Comment by emito-k** [comment]
The discord has been made and is being moderated
